database:
  host: 192.168.50.102
  username: kdc_user
  password: kdc123456
  name: kdc_database
  port: 5423
  driver: postgres
  driver: postgres
secret_key: uhbi49y823ry78923ijrgu803289u3ui23
service:
  port: 8009
  timeZone: "Asia/Phnom_Penh"
  logPtah: "logs/service-snap.log"
  http: true
  rabbitmq: false
  grcp: false
